package rip.tilly.bedwars.commands.arena;

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import rip.tilly.bedwars.BedWars;
import rip.tilly.bedwars.utils.CC;

public class ArenaCommand implements CommandExecutor {

    private BedWars main = BedWars.getInstance();

    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        Player player = (Player) sender;

        if (!player.hasPermission("bedwars.admin")) {
            player.sendMessage(CC.translate("&cNo permission"));

            return true;
        }

        if (args.length == 0) {
            player.sendMessage(CC.translate("&cUsage:"));
            player.sendMessage(CC.translate("  &c/arena"));
            player.sendMessage(CC.translate("  &c/arena manage (Opens arena manage menu)"));
            player.sendMessage(CC.translate("  &c/arena create <arena>"));
            player.sendMessage(CC.translate("  &c/arena icon <arena>"));
            player.sendMessage(CC.translate("  &c/arena enable <arena>"));
            player.sendMessage(CC.translate("  &c/arena disable <arena>"));
            player.sendMessage(CC.translate("  &c/arena a <arena>"));
            player.sendMessage(CC.translate("  &c/arena b <arena>"));
            player.sendMessage(CC.translate("  &c/arena min <arena>"));
            player.sendMessage(CC.translate("  &c/arena max <arena>"));
            player.sendMessage(CC.translate("  &c/arena teamAmin <arena>"));
            player.sendMessage(CC.translate("  &c/arena teamAmax <arena>"));
            player.sendMessage(CC.translate("  &c/arena teamBmin <arena>"));
            player.sendMessage(CC.translate("  &c/arena teamBmax <arena>"));
            player.sendMessage(CC.translate("  &c/arena deadzone <arena>"));
            player.sendMessage(CC.translate("  &c/arena buildmax <arena>"));
        } else {
            switch (args[0]) {

            }
        }

        return true;
    }
}
